alias note='$HOME/dotfiles/scripts/note'
alias notesync='$HOME/dotfiles/scripts/notesync'
alias notef='$HOME/dotfiles/scripts/notef'
alias mt27='. $HOME/venvs/mtpy27/bin/activate'
alias mt37='. $HOME/venvs/mtpy37/bin/activate'
alias umlvenv='. $HOME/.venvs/uml37/bin/activate && export UNCOVERML_SRC=/home/bren/uncoverml'
alias dcvenv='. $HOME/.venvs/detcap37/bin/activate'
alias hsvenv='. $HOME/venvs/hiperseis/bin/activate'
alias mtwvenv='. $HOME/.venvs/mtw/bin/activate'
alias pbvenv='. $HOME/.venvs/pbvenv/bin/activate'
