filetype on
set number

" tabs as four spaces
set expandtab
set shiftwidth=4
set softtabstop=4

"-------------------------------------------------------------------------------
" stuff for syntastic
"-------------------------------------------------------------------------------
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_cpp_checkers=['clang_check']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" syntastic pylint
let g:syntastic_python_checkers=['pylint']
let g:syntastic_python_pylint_args='--disable=C0103,C0111,C0113'
""-------------------------------------------------------------------------------
"" stuff for YCM
""-------------------------------------------------------------------------------
"" see:
"" https://github.com/Valloric/YouCompleteMe#user-content-the-gycm_show_diagnostics_ui-option
"" for why the following line is here
"let g:ycm_show_diagnostics_ui = 1
"
"" hilighting for YCM
"hi YcmErrorSection ctermbg=Red
"
"" close the preview window automatically
"" let g:ycm_autoclose_preview_window_after_completion=1

"-------------------------------------------------------------------------------
" colors
"-------------------------------------------------------------------------------
hi ColorColumn ctermbg=White
" columns at 80
set colorcolumn=80
" highlights chars in col 80 and beyond
"call matchadd('ColorColumn', '\%>79v.\+')

" hilight matching words in search
set hlsearch
" can be temporarilly stopped with
" :nohlsearch
hi Search ctermbg=DarkYellow ctermfg=White

syntax on
