filetype on
set number

" tabs as four spaces
set expandtab
set shiftwidth=4
set softtabstop=4

" ALE
let g:ale_echo_msg_format = '[%linter%] %code%: %s'

"-------------------------------------------------------------------------------
" colors
"-------------------------------------------------------------------------------
hi ColorColumn ctermbg=0 guibg=lightgrey
set colorcolumn=72,100

set hlsearch
hi Search ctermbg=DarkYellow ctermfg=White

syntax on
