#! /usr/bin/env python

import subprocess

def main():
    git_status = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, check=True
    ).stdout.decode("utf-8").split('\n')
    for line in git_status:
        if line.startswith(' M'):
            path = line.split()[-1]
            subprocess.run(["git", "diff", path])
            add = input("Add this file? [y|N]")
            if add.lower() == 'y':
                subprocess.run(["git", "add", path])

if __name__ == "__main__":
    main()
